package matriz;

import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author DiegoArmando
 */
public class GUIPrincipal extends javax.swing.JFrame {

    private PnlMatriz pnlMatrizOrg;
    private PnlMatriz pnlMatrizInv;
    private PnlAyuda pnlAyuda;
    private GUIPrincipal frame;
    

    /**
     * Creates new form GUI
     */

    public GUIPrincipal() {
        super("Matriz Inversa");
        initComponents();

        pnlMatrizOrg = new PnlMatriz(PnlMatriz.ENABLE);
        pnlIzquierdo.add(pnlMatrizOrg);
        pnlMatrizInv = new PnlMatriz(PnlMatriz.DISABLE);
        pnlDerecho.add(pnlMatrizInv);
    }

    /**
     * Retorna un objeto Image para ser utilizado como ícono en la barra de
     * título.
     *
     * @return
     */
    @Override
    public java.awt.Image getIconImage() {
        java.awt.Image retValue = java.awt.Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Recursos/Yes6.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlIzquierdo = new javax.swing.JPanel();
        pnlDerecho = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnRandom = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        Encuesta = new javax.swing.JMenu();
        IngresarEncuesta = new javax.swing.JMenuItem();
        AcercaDe = new javax.swing.JMenu();
        Ayuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setName("GUIPrincipal"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Matriz Original");

        pnlIzquierdo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlIzquierdo.setMaximumSize(new java.awt.Dimension(600, 600));
        pnlIzquierdo.setMinimumSize(new java.awt.Dimension(500, 500));
        pnlIzquierdo.setName(""); // NOI18N
        pnlIzquierdo.setPreferredSize(new java.awt.Dimension(500, 500));
        pnlIzquierdo.setLayout(new java.awt.BorderLayout());

        pnlDerecho.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlDerecho.setMaximumSize(new java.awt.Dimension(600, 600));
        pnlDerecho.setMinimumSize(new java.awt.Dimension(500, 500));
        pnlDerecho.setPreferredSize(new java.awt.Dimension(500, 500));
        pnlDerecho.setLayout(new java.awt.BorderLayout());

        btnRandom.setText("Aleatorio");
        btnRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRandomActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnRandom)
                .addGap(18, 18, 18)
                .addComponent(btnReset)
                .addGap(18, 18, 18)
                .addComponent(btnCalcular)
                .addGap(46, 46, 46)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRandom)
                        .addComponent(btnReset)
                        .addComponent(btnCalcular)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Matriz Inversa");

        Encuesta.setMnemonic('E');
        Encuesta.setText("Matriz");

        IngresarEncuesta.setMnemonic('I');
        IngresarEncuesta.setText("Definir tamaño");
        IngresarEncuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarEncuestaActionPerformed(evt);
            }
        });
        Encuesta.add(IngresarEncuesta);

        menuBar.add(Encuesta);

        AcercaDe.setMnemonic('A');
        AcercaDe.setText("Acerca de");

        Ayuda.setMnemonic('G');
        Ayuda.setText("Ayuda");
        Ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AyudaActionPerformed(evt);
            }
        });
        AcercaDe.add(Ayuda);

        menuBar.add(AcercaDe);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDerecho, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlDerecho, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresarEncuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarEncuestaActionPerformed
        String resp = JOptionPane.showInputDialog(this, "Ingrese el tamaño de la matriz:", "Tamaño Matriz Cuadrada", JOptionPane.QUESTION_MESSAGE);

        if (resp != null) {
            int tamano = Integer.parseInt(resp);
            if (tamano >= 2 && tamano <= 20) {
                //Si ya está el otro Jpanel añadido al contenedor, entonces se elimina
                pnlIzquierdo.removeAll();
                pnlDerecho.removeAll();
                //Adiciono botones al FramePrincipal
                pnlMatrizOrg = new PnlMatriz(tamano, PnlMatriz.ENABLE);
                pnlIzquierdo.add(pnlMatrizOrg);
                pnlMatrizInv = new PnlMatriz(tamano, PnlMatriz.DISABLE);
                pnlDerecho.add(pnlMatrizInv);
                //Hacemos que el JFrame tenga el tamaño de todos sus elementos
                repaint();
                pack();
            } else {

            }
        }
    }//GEN-LAST:event_IngresarEncuestaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.out.println("Saliendo...");
    }//GEN-LAST:event_formWindowClosing

    private void AyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AyudaActionPerformed
        // TODO add your handling code here:

//         pnlIzquierdo.removeAll();
//                pnlDerecho.removeAll();
        pnlAyuda = new PnlAyuda();

        JDialog dialog = new JDialog();
        dialog.setContentPane(pnlAyuda);
        //Centramos nuestro jDialog
        //dialog.setLocationRelativeTo(null);
        
        //La hacemos modal
        dialog.setModal(true);
        //Establecemos dimensiones.
        //dialog.setMaximumSize(new Dimension(1080, 920));
        //dialog.setMinimumSize(new Dimension(720, 420));
        dialog.setSize(720, 450);
        dialog.setLocationRelativeTo(frame); 
               
        //Establecemos un título para el jDialog
        dialog.setTitle("Ayuda");
        //La hacemos visible.
        dialog.setVisible(true);

    }//GEN-LAST:event_AyudaActionPerformed

    private void btnRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRandomActionPerformed
        pnlMatrizOrg.reset();
        pnlMatrizInv.reset();
        pnlMatrizOrg.llenar();
    }//GEN-LAST:event_btnRandomActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        pnlMatrizOrg.reset();
        pnlMatrizInv.reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        pnlMatrizOrg.llenar(0);
        pnlMatrizInv.matrizInversa(pnlMatrizOrg);
    }//GEN-LAST:event_btnCalcularActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AcercaDe;
    private javax.swing.JMenuItem Ayuda;
    private javax.swing.JMenu Encuesta;
    private javax.swing.JMenuItem IngresarEncuesta;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnRandom;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel pnlDerecho;
    private javax.swing.JPanel pnlIzquierdo;
    // End of variables declaration//GEN-END:variables
}
